#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# PreToolUse hook: Guard against unsafe writes
# Reads project-config.yaml to determine which checks apply.
# Returns exit 2 with deny JSON to block the operation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="$PROJECT_ROOT/.claude/project-config.yaml"

# Read tool input from stdin
INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null || true)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null || true)
CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // .tool_input.file_text // empty' 2>/dev/null || true)

# Skip if no file path
[ -z "$FILE_PATH" ] && exit 0

# Helper: read config value with awk
config_val() {
    local key="$1"
    awk -v key="$key" '$1 == key":" { gsub(/"/, "", $2); print $2 }' "$CONFIG" 2>/dev/null
}

deny() {
    local reason="$1"
    echo '{"decision": "deny", "reason": "'"$reason"'"}' >&2
    exit 2
}

# ─── Check 1: Block writes to generated/ directory ───
SCHEMA_ENABLED=$(config_val "enabled" | head -1)
if [ "$SCHEMA_ENABLED" = "true" ]; then
    GENERATED_DIR=$(config_val "generated_types")
    GENERATED_DIR="${GENERATED_DIR%/*}"  # Get directory part
    if [[ "$FILE_PATH" == *"$GENERATED_DIR"* ]] && [ -n "$GENERATED_DIR" ]; then
        deny "Do not write to generated directory directly. Use @schema-guardian subagent instead."
    fi

    # ─── Check 2: Block writes to schema files ───
    SCHEMA_DEFS=$(config_val "definitions")
    SCHEMA_CFG=$(config_val "config_file")
    if [[ "$FILE_PATH" == *"$SCHEMA_DEFS"* ]] || [[ "$FILE_PATH" == *"$SCHEMA_CFG"* ]]; then
        deny "Do not modify schema files directly. Use @schema-guardian subagent instead."
    fi

    # ─── Check 5: Block inline type definitions when schema enabled ───
    if [ -n "$CONTENT" ]; then
        if echo "$CONTENT" | grep -qE '(interface |type .*= \{|enum )' 2>/dev/null; then
            SRC_DIR=$(config_val "source")
            if [[ "$FILE_PATH" == *"$SRC_DIR"* ]]; then
                # Allow in test files and type definition files
                if [[ "$FILE_PATH" != *"test"* ]] && [[ "$FILE_PATH" != *".d.ts"* ]]; then
                    deny "Do not define domain types inline. Import from generated types instead."
                fi
            fi
        fi
    fi
fi

# ─── Check 3: Block Node.js builtins in CloudFlare Workers ───
RUNTIME=$(config_val "runtime")
if [ "$RUNTIME" = "cloudflare-workers" ] && [ -n "$CONTENT" ]; then
    SRC_DIR=$(config_val "source")
    if [[ "$FILE_PATH" == *"$SRC_DIR"* ]]; then
        for builtin in "require('fs')" "require('path')" "require('os')" "require('child_process')" \
                       "from 'fs'" "from 'path'" "from 'os'" "from 'child_process'" \
                       "from 'node:fs'" "from 'node:path'" "from 'node:os'"; do
            if echo "$CONTENT" | grep -qF "$builtin" 2>/dev/null; then
                deny "Node.js builtin '$builtin' not available in CloudFlare Workers runtime. Use Workers APIs instead."
            fi
        done

        # ─── Check 4: Block process.env in Workers ───
        if echo "$CONTENT" | grep -qF "process.env" 2>/dev/null; then
            deny "process.env not available in CloudFlare Workers. Use env bindings (c.env.VAR) instead."
        fi
    fi
fi

# All checks passed
exit 0
