#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Risk classification — reads git diff, outputs RISK_LEVEL.
# Used by pr-architect subagent and commit-push-pr command.

set -uo pipefail

PROJECT_ROOT="${1:-.}"
RISK="LOW"

# Get changed files
CHANGED=$(git -C "$PROJECT_ROOT" diff --name-only HEAD~1 2>/dev/null || \
          git -C "$PROJECT_ROOT" diff --cached --name-only 2>/dev/null || echo "")

[ -z "$CHANGED" ] && { echo "RISK_LEVEL=UNKNOWN"; exit 0; }

# CRITICAL: schema, auth, payment, deployment config, secrets
CRITICAL_PATTERNS="schema/|auth|payment|stripe|secrets|\.env|wrangler\.toml|deploy|migration"
if echo "$CHANGED" | grep -qiE "$CRITICAL_PATTERNS"; then
    RISK="CRITICAL"
fi

# HIGH: new API handlers, database changes, calculation logic
HIGH_PATTERNS="handler|route|api/|\.sql|calculator|engine"
if [ "$RISK" != "CRITICAL" ] && echo "$CHANGED" | grep -qiE "$HIGH_PATTERNS"; then
    RISK="HIGH"
fi

# MEDIUM: new source files, test changes, config changes
MEDIUM_PATTERNS="^src/.*new|config\.|\.config|test"
if [ "$RISK" = "LOW" ] && echo "$CHANGED" | grep -qiE "$MEDIUM_PATTERNS"; then
    RISK="MEDIUM"
fi

# LOW: documentation, comments, formatting, dev tooling
# (default if nothing else matched)

# Additional stats
FILE_COUNT=$(echo "$CHANGED" | wc -l)
INSERTIONS=$(git -C "$PROJECT_ROOT" diff --shortstat HEAD~1 2>/dev/null | grep -oP '\d+ insertion' | grep -oP '\d+' || echo "0")
DELETIONS=$(git -C "$PROJECT_ROOT" diff --shortstat HEAD~1 2>/dev/null | grep -oP '\d+ deletion' | grep -oP '\d+' || echo "0")

# Large changes bump risk up one level
TOTAL_CHANGES=$((${INSERTIONS:-0} + ${DELETIONS:-0}))
if [ "$TOTAL_CHANGES" -gt 500 ] && [ "$RISK" = "LOW" ]; then RISK="MEDIUM"; fi
if [ "$TOTAL_CHANGES" -gt 1000 ] && [ "$RISK" = "MEDIUM" ]; then RISK="HIGH"; fi

echo "RISK_LEVEL=$RISK"
echo "FILES_CHANGED=$FILE_COUNT"
echo "LINES_CHANGED=$TOTAL_CHANGES"
echo "CRITICAL_FILES=$(echo "$CHANGED" | grep -ciE "$CRITICAL_PATTERNS" || echo 0)"
