#!/usr/bin/env node
// Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
// PostToolUse hook: Log tool usage metrics to session JSONL file.
// Lightweight and non-blocking.

import { appendFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';

// Read tool event from stdin
let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
    try {
        const event = JSON.parse(input);
        const toolName = event.tool_name || 'unknown';
        const timestamp = new Date().toISOString();
        const date = timestamp.slice(0, 10);
        
        // Find project root (walk up from script location)
        let dir = dirname(new URL(import.meta.url).pathname);
        while (dir !== '/' && !existsSync(join(dir, '.claude'))) {
            dir = dirname(dir);
        }
        
        const metricsDir = join(dir, '.claude', 'metrics');
        if (!existsSync(metricsDir)) {
            mkdirSync(metricsDir, { recursive: true });
        }
        
        const logFile = join(metricsDir, `session-${date}.jsonl`);
        const entry = {
            timestamp,
            tool: toolName,
            agent: process.env.IVAN_AGENT_ROLE || 'unknown',
            task: event.task_id || null
        };
        
        appendFileSync(logFile, JSON.stringify(entry) + '\n');
    } catch {
        // Non-blocking: silently ignore errors
    }
});
