#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Pre-review automated checks — invoked by Reviewer agent, not a hook.
# Runs structural code analysis to flag items for focused human review.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="$PROJECT_ROOT/.claude/project-config.yaml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

config_val() {
    awk -v key="$1" '$1 == key":" { gsub(/"/, "", $2); print $2 }' "$CONFIG" 2>/dev/null
}

ISSUES=0
WARNINGS=0

flag_issue() { echo -e "  ${RED}■${NC} ISSUE: $1"; ((ISSUES++)); }
flag_warn()  { echo -e "  ${YELLOW}▲${NC} WARN:  $1"; ((WARNINGS++)); }
flag_ok()    { echo -e "  ${GREEN}✓${NC} OK:    $1"; }

echo -e "${BLUE}═══ Pre-Review Checks ═══${NC}"
echo ""

# Get changed files
CHANGED_FILES=$(git -C "$PROJECT_ROOT" diff --name-only HEAD~1 2>/dev/null || git -C "$PROJECT_ROOT" diff --cached --name-only 2>/dev/null || echo "")

if [ -z "$CHANGED_FILES" ]; then
    echo "No changed files detected. Checking all source files."
    SRC_DIR=$(config_val "source")
    CHANGED_FILES=$(find "$PROJECT_ROOT/${SRC_DIR:-src}" -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' -o -name '*.py' 2>/dev/null | sed "s|$PROJECT_ROOT/||")
fi

# 1. Typecheck + Lint
echo -e "${BLUE}[1/6] Quality commands${NC}"
TYPECHECK_CMD=$(config_val "typecheck_command")
LINT_CMD=$(config_val "lint_command")
[ -n "$TYPECHECK_CMD" ] && { (cd "$PROJECT_ROOT" && eval "$TYPECHECK_CMD" >/dev/null 2>&1) && flag_ok "Typecheck passes" || flag_issue "Typecheck fails"; }
[ -n "$LINT_CMD" ] && { (cd "$PROJECT_ROOT" && eval "$LINT_CMD" >/dev/null 2>&1) && flag_ok "Lint passes" || flag_issue "Lint fails"; }

# 2. Import audit (inline types when schema enabled)
echo -e "${BLUE}[2/6] Import audit${NC}"
SCHEMA_ENABLED=$(config_val "enabled" | head -1)
if [ "$SCHEMA_ENABLED" = "true" ]; then
    SRC_DIR=$(config_val "source")
    INLINE_TYPES=$(echo "$CHANGED_FILES" | while read -r f; do
        [[ "$f" == *"$SRC_DIR"* ]] && [[ "$f" != *"test"* ]] && [[ "$f" != *".d.ts"* ]] && \
        grep -ln 'interface \|type .*= {' "$PROJECT_ROOT/$f" 2>/dev/null
    done)
    if [ -n "$INLINE_TYPES" ]; then
        flag_warn "Inline type definitions found (should import from generated types):"
        echo "$INLINE_TYPES" | head -5 | sed 's/^/    /'
    else
        flag_ok "No inline type definitions in source files"
    fi
else
    flag_ok "Schema-first not enabled — skipping import audit"
fi

# 3. Hardcoded values
echo -e "${BLUE}[3/6] Hardcoded values${NC}"
HARDCODED=$(echo "$CHANGED_FILES" | while read -r f; do
    [ -f "$PROJECT_ROOT/$f" ] && grep -n 'localhost\|127\.0\.0\.1\|hardcoded\|TODO.*hack\|FIXME.*temp' "$PROJECT_ROOT/$f" 2>/dev/null | head -3
done)
if [ -n "$HARDCODED" ]; then
    flag_warn "Potential hardcoded values found"
    echo "$HARDCODED" | head -5 | sed 's/^/    /'
else
    flag_ok "No obvious hardcoded values"
fi

# 4. Error handling patterns
echo -e "${BLUE}[4/6] Error handling${NC}"
BARE_CATCH=$(echo "$CHANGED_FILES" | while read -r f; do
    [ -f "$PROJECT_ROOT/$f" ] && grep -n 'catch\s*{' "$PROJECT_ROOT/$f" 2>/dev/null | head -3
done)
if [ -n "$BARE_CATCH" ]; then
    flag_warn "Bare catch blocks (no error parameter)"
    echo "$BARE_CATCH" | head -5 | sed 's/^/    /'
else
    flag_ok "Error handling looks reasonable"
fi

# 5. Runtime compatibility
echo -e "${BLUE}[5/6] Runtime compatibility${NC}"
RUNTIME=$(config_val "runtime")
if [ "$RUNTIME" = "cloudflare-workers" ]; then
    NODE_BUILTINS=$(echo "$CHANGED_FILES" | while read -r f; do
        SRC_DIR=$(config_val "source")
        [[ "$f" == *"$SRC_DIR"* ]] && [ -f "$PROJECT_ROOT/$f" ] && \
        grep -n "require('fs')\|require('path')\|from 'fs'\|from 'path'\|from 'os'\|process\.env\." "$PROJECT_ROOT/$f" 2>/dev/null | head -3
    done)
    if [ -n "$NODE_BUILTINS" ]; then
        flag_issue "Node.js builtins/process.env in Workers code"
        echo "$NODE_BUILTINS" | head -5 | sed 's/^/    /'
    else
        flag_ok "No Node.js builtins in Workers source"
    fi
else
    flag_ok "Runtime: $RUNTIME — no special constraints"
fi

# 6. Schema regen check
echo -e "${BLUE}[6/6] Schema consistency${NC}"
if [ "$SCHEMA_ENABLED" = "true" ]; then
    SCHEMA_DEFS=$(config_val "definitions")
    SCHEMA_GEN=$(config_val "generated_types")
    if [ -n "$SCHEMA_DEFS" ] && [ -n "$SCHEMA_GEN" ]; then
        SCHEMA_CHANGED=$(echo "$CHANGED_FILES" | grep -c "$SCHEMA_DEFS" || true)
        TYPES_CHANGED=$(echo "$CHANGED_FILES" | grep -c "$SCHEMA_GEN" || true)
        if [ "$SCHEMA_CHANGED" -gt 0 ] && [ "$TYPES_CHANGED" -eq 0 ]; then
            flag_issue "Schema changed but generated types not regenerated!"
        else
            flag_ok "Schema and generated types consistent"
        fi
    fi
else
    flag_ok "Schema-first not enabled"
fi

echo ""
echo -e "Summary: ${RED}$ISSUES issues${NC}, ${YELLOW}$WARNINGS warnings${NC}"
[ "$ISSUES" -gt 0 ] && echo -e "${RED}⚠ Issues found — Reviewer should focus on these${NC}"
[ "$ISSUES" -eq 0 ] && [ "$WARNINGS" -eq 0 ] && echo -e "${GREEN}✓ All pre-review checks passed${NC}"
echo ""
