#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Stop hook (non-blocking): Inject handoff reminder if a task is in progress.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="$PROJECT_ROOT/.claude/project-config.yaml"

# Read handoff dir from config
HANDOFFS_DIR=$(awk '$1 == "handoffs:" { gsub(/"/, "", $2); print $2 }' "$CONFIG" 2>/dev/null)
HANDOFFS_DIR="${HANDOFFS_DIR:-docs/agent-comms}"

# Check for active tasks
ACTIVE_TASKS=$(find "$PROJECT_ROOT/$HANDOFFS_DIR" -name "status.json" -exec grep -l '"active"' {} \; 2>/dev/null | head -3)

if [ -n "$ACTIVE_TASKS" ]; then
    AGENT_ROLE="${IVAN_AGENT_ROLE:-unknown}"
    echo ""
    echo "━━━ Handoff Reminder ━━━"
    echo "You have active workflow tasks. Before ending this session:"
    echo "  1. Run /agent-handoff to create a structured handoff"
    echo "  2. Or run /chat-completion for a full session wrap-up"
    echo ""
    echo "Active tasks:"
    for status_file in $ACTIVE_TASKS; do
        TASK_DIR=$(dirname "$status_file")
        TASK_ID=$(basename "$TASK_DIR")
        CURRENT=$(jq -r '.current_agent // "unknown"' "$status_file" 2>/dev/null)
        echo "  • $TASK_ID (current: $CURRENT)"
    done
    echo "━━━━━━━━━━━━━━━━━━━━━━━"
fi

exit 0
