#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Stop hook (blocking): Run quality gates before allowing agent to stop.
# Reads commands from project-config.yaml.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="$PROJECT_ROOT/.claude/project-config.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Helper: read config value
config_val() {
    awk -v key="$1" '$1 == key":" { gsub(/"/, "", $2); print $2 }' "$CONFIG" 2>/dev/null
}

PASS=0
FAIL=0
SKIP=0

run_check() {
    local name="$1"
    local cmd="$2"
    
    if [ -z "$cmd" ] || [ "$cmd" = '""' ]; then
        echo -e "  ${YELLOW}○${NC} $name — skipped (not configured)"
        ((SKIP++))
        return 0
    fi
    
    echo -ne "  ${BLUE}●${NC} $name... "
    local output
    local start_time=$SECONDS
    if output=$(cd "$PROJECT_ROOT" && eval "$cmd" 2>&1); then
        local elapsed=$((SECONDS - start_time))
        echo -e "${GREEN}✓ passed${NC} (${elapsed}s)"
        ((PASS++))
        return 0
    else
        local elapsed=$((SECONDS - start_time))
        echo -e "${RED}✗ FAILED${NC} (${elapsed}s)"
        echo "$output" | head -20 | sed 's/^/    /'
        ((FAIL++))
        return 1
    fi
}

echo ""
echo -e "${BLUE}═══ Quality Gates ═══${NC}"
echo ""

TYPECHECK_CMD=$(config_val "typecheck_command")
LINT_CMD=$(config_val "lint_command")
TEST_CMD=$(config_val "test_command")

# Check for uncommitted schema changes
SCHEMA_ENABLED=$(config_val "enabled" | head -1)
if [ "$SCHEMA_ENABLED" = "true" ]; then
    SCHEMA_DEFS=$(config_val "definitions")
    if [ -n "$SCHEMA_DEFS" ] && [ -f "$PROJECT_ROOT/$SCHEMA_DEFS" ]; then
        if git -C "$PROJECT_ROOT" diff --name-only 2>/dev/null | grep -q "$SCHEMA_DEFS"; then
            GEN_CMD=$(config_val "generate_command")
            if [ -n "$GEN_CMD" ]; then
                run_check "Schema regeneration" "$GEN_CMD" || true
            fi
        fi
    fi
fi

run_check "Typecheck" "$TYPECHECK_CMD" || true
run_check "Lint" "$LINT_CMD" || true
run_check "Tests" "$TEST_CMD" || true

echo ""
echo -e "Results: ${GREEN}$PASS passed${NC}, ${RED}$FAIL failed${NC}, ${YELLOW}$SKIP skipped${NC}"

if [ "$FAIL" -gt 0 ]; then
    echo -e "${RED}⚠ Quality gates failed — review issues above${NC}"
    echo ""
    # Blocking hook: exit 1 prevents stop
    exit 1
else
    echo -e "${GREEN}✓ All quality gates passed${NC}"
    echo ""
    exit 0
fi
