"""IWO Ops Actions Register — structured tracking of human-required operational tasks.

Ops Actions are discrete manual tasks generated by the pipeline (migrations, secrets,
DNS changes, browser verifications) that require human execution. This module provides
the data model, persistence, deduplication, and query interface.

Storage: docs/agent-comms/.ops-actions.json (append-only, filesystem-based).
"""

import hashlib
import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal, Optional

from pydantic import BaseModel, Field

log = logging.getLogger("iwo.ops_actions")

# --- Priority and Category Classification ---

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "migration": ["migration", "migrate", "d1 execute", "d1 migrations", "wrangler d1"],
    "secret": ["secret", "wrangler secret", "api key", "api_key", "token"],
    "dns": ["dns", "cname", "a record", "mx record", "txt record", "spf", "dkim", "dmarc"],
    "webhook": ["webhook", "n8n", "hook"],
    "verification": ["verify", "browser", "visual", "check", "confirm", "end-to-end"],
    "config": ["config", "wrangler.toml", "environment", "binding", "kv namespace", "r2 bucket"],
    "email_infra": ["email", "resend", "listmonk", "smtp", "spf record", "dkim"],
}

CRITICAL_PATTERNS: list[re.Pattern] = [
    re.compile(p, re.IGNORECASE) for p in [
        r'must\s+(run|create|configure|set|apply|execute)',
        r'wrangler\s+(secret|d1\s+migrations)',
        r'not\s+yet\s+(set|configured|created|applied)',
        r'human\s+(must|task|action)',
        r'\bDNS\b.*\b(CNAME|A\s+record|MX)\b',
        r'secrets?\s+not\s+(set|configured)',
        r'migration.*not\s+(applied|run)',
        r'required.*before\s+deploy',
    ]
]

WARNING_PATTERNS: list[re.Pattern] = [
    re.compile(p, re.IGNORECASE) for p in [
        r'(webhook|n8n).*\b(configure|setup|connect)\b',
        r'config.*\b(update|change|add)\b',
        r'(erp|crm).*\b(integrate|connect|configure)\b',
        r'stripe.*\b(configure|webhook|connect)\b',
    ]
]

VERIFICATION_PATTERNS: list[re.Pattern] = [
    re.compile(p, re.IGNORECASE) for p in [
        r'(human|user)\s+must\s+verify',
        r'browser[\s-]verif(y|ication)',
        r'visual(ly)?\s+verif',
        r'end-to-end.*requires?\s+(auth|browser|session)',
        r'manually\s+(test|check|confirm)',
    ]
]


# --- Data Model ---

OpsActionStatus = Literal["pending", "in_progress", "completed", "skipped"]
OpsActionPriority = Literal["critical", "warning", "info"]
OpsActionCategory = Literal[
    "migration", "secret", "dns", "webhook", "verification",
    "config", "email_infra", "other"
]


class OpsAction(BaseModel):
    """A discrete manual task required by the pipeline."""
    id: str
    spec_id: str
    title: str
    description: str
    category: OpsActionCategory = "other"
    priority: OpsActionPriority = "info"
    status: OpsActionStatus = "pending"
    verification_cmd: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    source_agent: str = "unknown"
    source_sequence: int = 0
    fingerprint: str = ""
    resolved_at: Optional[str] = None
    resolved_by: Optional[str] = None
    notes: Optional[str] = None
    auto_extracted: bool = False
    stale_since: Optional[str] = None
    priority_override: Optional[OpsActionPriority] = None

    @property
    def effective_priority(self) -> OpsActionPriority:
        """Priority with manual override support."""
        return self.priority_override or self.priority


def _normalize_text(text: str) -> str:
    """Normalize text for fingerprinting: lowercase, strip sequence refs, collapse whitespace."""
    text = text.lower().strip()
    # Strip sequence-specific references like "#003", "sequence 5", "(#12)"
    text = re.sub(r'#\d+', '', text)
    text = re.sub(r'sequence\s+\d+', '', text)
    text = re.sub(r'\(#\d+\)', '', text)
    # Collapse whitespace AFTER stripping refs
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


def compute_fingerprint(spec_id: str, text: str) -> str:
    """SHA-256 fingerprint for deduplication: hash of spec_id + normalized text."""
    normalized = _normalize_text(text)
    raw = f"{spec_id}:{normalized}"
    return f"sha256:{hashlib.sha256(raw.encode()).hexdigest()[:16]}"


def classify_priority(text: str) -> OpsActionPriority:
    """Classify action priority based on keyword patterns."""
    for pattern in CRITICAL_PATTERNS:
        if pattern.search(text):
            return "critical"
    for pattern in WARNING_PATTERNS:
        if pattern.search(text):
            return "warning"
    for pattern in VERIFICATION_PATTERNS:
        if pattern.search(text):
            return "info"
    return "info"


def classify_category(text: str) -> OpsActionCategory:
    """Classify action category based on keyword matching."""
    text_lower = text.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        for keyword in keywords:
            if keyword in text_lower:
                return category  # type: ignore
    return "other"


def _next_id(existing_ids: list[str]) -> str:
    """Generate next sequential ID like ops-20260226-001."""
    today = datetime.now(timezone.utc).strftime("%Y%m%d")
    prefix = f"ops-{today}-"
    max_num = 0
    for eid in existing_ids:
        if eid.startswith(prefix):
            try:
                num = int(eid[len(prefix):])
                max_num = max(max_num, num)
            except ValueError:
                pass
    # Also check other dates to avoid collision in global numbering
    for eid in existing_ids:
        if eid.startswith("ops-"):
            try:
                num = int(eid.split("-")[-1])
                max_num = max(max_num, num)
            except ValueError:
                pass
    return f"{prefix}{max_num + 1:03d}"


# --- Register ---

class OpsActionsRegister:
    """Persistent register of operational actions, stored as JSON on filesystem."""

    def __init__(self, path: Path):
        self.path = path
        self.actions: list[OpsAction] = []
        self._fingerprints: set[str] = set()

    def load(self) -> None:
        """Load register from JSON file. Creates empty register if file missing."""
        if not self.path.exists():
            self.actions = []
            self._fingerprints = set()
            log.info(f"Ops actions register not found at {self.path}, starting empty")
            return
        try:
            with open(self.path) as f:
                data = json.load(f)
        except json.JSONDecodeError:
            # Possible mid-write by Agent 007 — retry once after 1s
            log.warning(f"JSONDecodeError reading {self.path}, retrying in 1s...")
            import time
            time.sleep(1)
            try:
                with open(self.path) as f:
                    data = json.load(f)
            except Exception as e2:
                log.error(f"Retry failed for ops register: {e2}")
                self.actions = []
                self._fingerprints = set()
                return
        except Exception as e:
            log.error(f"Failed to load ops actions register: {e}")
            self.actions = []
            self._fingerprints = set()
            return
        raw_actions = data.get("actions", [])
        self.actions = [OpsAction(**a) for a in raw_actions]
        self._fingerprints = {a.fingerprint for a in self.actions if a.fingerprint}
        log.info(f"Loaded {len(self.actions)} ops actions from {self.path}")

    def save(self) -> None:
        """Persist register to JSON file."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "version": "1.0",
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "actions": [a.model_dump() for a in self.actions],
        }
        with open(self.path, "w") as f:
            json.dump(data, f, indent=2)
        log.info(f"Saved {len(self.actions)} ops actions to {self.path}")

    def add(self, action: OpsAction) -> bool:
        """Add an action if not a duplicate (fingerprint dedup). Returns True if added."""
        if action.fingerprint and action.fingerprint in self._fingerprints:
            log.debug(f"Duplicate ops action skipped: {action.fingerprint} ({action.title[:50]})")
            return False
        if not action.id:
            action.id = _next_id([a.id for a in self.actions])
        if not action.fingerprint:
            action.fingerprint = compute_fingerprint(action.spec_id, action.description)
            if action.fingerprint in self._fingerprints:
                log.debug(f"Duplicate ops action skipped (computed): {action.title[:50]}")
                return False
        self.actions.append(action)
        self._fingerprints.add(action.fingerprint)
        log.info(f"Ops action added: [{action.priority}] {action.id} — {action.title}")
        return True

    def resolve(self, action_id: str, resolved_by: str = "human", notes: Optional[str] = None) -> bool:
        """Mark an action as completed. Returns True if found and updated."""
        for action in self.actions:
            if action.id == action_id:
                action.status = "completed"
                action.resolved_at = datetime.now(timezone.utc).isoformat()
                action.resolved_by = resolved_by
                if notes:
                    action.notes = notes
                log.info(f"Ops action resolved: {action_id} by {resolved_by}")
                return True
        log.warning(f"Ops action not found: {action_id}")
        return False

    def skip(self, action_id: str, reason: str) -> bool:
        """Mark an action as skipped with reason. Returns True if found."""
        for action in self.actions:
            if action.id == action_id:
                action.status = "skipped"
                action.resolved_at = datetime.now(timezone.utc).isoformat()
                action.notes = f"Skipped: {reason}"
                log.info(f"Ops action skipped: {action_id} — {reason}")
                return True
        log.warning(f"Ops action not found: {action_id}")
        return False

    def mark_stale(self, action_id: str) -> bool:
        """Flag an action as possibly resolved (source text disappeared from handoffs)."""
        for action in self.actions:
            if action.id == action_id:
                if not action.stale_since:
                    action.stale_since = datetime.now(timezone.utc).isoformat()
                    log.info(f"Ops action marked stale: {action_id}")
                return True
        return False

    def clear_stale(self, action_id: str) -> bool:
        """Clear stale flag (action reappeared in newer handoff)."""
        for action in self.actions:
            if action.id == action_id:
                action.stale_since = None
                return True
        return False

    def get_pending(self, priority: Optional[OpsActionPriority] = None) -> list[OpsAction]:
        """Get pending actions, optionally filtered by priority."""
        result = [a for a in self.actions if a.status == "pending"]
        if priority:
            result = [a for a in result if a.effective_priority == priority]
        # Sort: critical first, then warning, then info
        priority_order = {"critical": 0, "warning": 1, "info": 2}
        result.sort(key=lambda a: priority_order.get(a.effective_priority, 3))
        return result

    def get_by_spec(self, spec_id: str) -> list[OpsAction]:
        """Get all actions for a specific spec."""
        return [a for a in self.actions if a.spec_id == spec_id]

    def get_pending_for_spec(self, spec_id: str, priority: Optional[OpsActionPriority] = None) -> list[OpsAction]:
        """Get pending actions for a specific spec, optionally filtered by priority."""
        result = [a for a in self.actions if a.spec_id == spec_id and a.status == "pending"]
        if priority:
            result = [a for a in result if a.effective_priority == priority]
        return result

    def get_by_id(self, action_id: str) -> Optional[OpsAction]:
        """Find an action by ID."""
        for a in self.actions:
            if a.id == action_id:
                return a
        return None

    def get_summary(self) -> dict:
        """Counts by priority × status."""
        summary: dict[str, dict[str, int]] = {}
        for action in self.actions:
            p = action.effective_priority
            s = action.status
            if p not in summary:
                summary[p] = {}
            summary[p][s] = summary[p].get(s, 0) + 1
        # Add totals
        totals = {"pending": 0, "completed": 0, "skipped": 0, "in_progress": 0}
        for p_counts in summary.values():
            for s, c in p_counts.items():
                totals[s] = totals.get(s, 0) + c
        summary["total"] = totals
        return summary

    def pending_count(self, priority: Optional[OpsActionPriority] = None) -> int:
        """Quick count of pending actions."""
        return len(self.get_pending(priority))

    def has_pending_critical(self, spec_id: Optional[str] = None) -> bool:
        """Check if there are any pending critical actions, optionally for a specific spec."""
        if spec_id:
            return len(self.get_pending_for_spec(spec_id, "critical")) > 0
        return len(self.get_pending("critical")) > 0

