#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Interactive installer for Ivan's Workflow framework
# Usage: ~/projects/ivans-workflow/install.sh [target-directory]

set -euo pipefail

# ─── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

FRAMEWORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Helper Functions ──────────────────────────────────────────

print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  Ivan's Workflow — Project Installer${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

prompt() {
    local var_name="$1" prompt_text="$2" default="$3"
    local input
    if [ -n "$default" ]; then
        read -rp "$(echo -e "${CYAN}$prompt_text${NC} [$default]: ")" input
        eval "$var_name=\"${input:-$default}\""
    else
        read -rp "$(echo -e "${CYAN}$prompt_text${NC}: ")" input
        eval "$var_name=\"$input\""
    fi
}

menu() {
    local var_name="$1" prompt_text="$2"
    shift 2
    local options=("$@")
    echo -e "${CYAN}$prompt_text${NC}"
    for i in "${!options[@]}"; do
        echo "  $((i+1))) ${options[$i]}"
    done
    local choice
    read -rp "  Choice [1]: " choice
    choice="${choice:-1}"
    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#options[@]}" ]; then
        eval "$var_name=\"${options[$((choice-1))]}\""
    else
        eval "$var_name=\"${options[0]}\""
    fi
}

link_or_copy() {
    local src="$1" dest="$2"
    # If dest exists and is NOT a symlink to our framework, skip it (idempotent)
    if [ -e "$dest" ] && [ ! -L "$dest" ]; then
        echo -e "  ${YELLOW}SKIP${NC} $dest (exists, not a framework symlink)"
        return 0
    fi
    # Remove old symlink if present
    rm -f "$dest"
    if [ "$LINK_MODE" = "symlink" ]; then
        ln -s "$src" "$dest"
        echo -e "  ${GREEN}LINK${NC} $dest → $src"
    else
        cp -r "$src" "$dest"
        echo -e "  ${GREEN}COPY${NC} $dest"
    fi
}

link_dir_contents() {
    local src_dir="$1" dest_dir="$2"
    mkdir -p "$dest_dir"
    for f in "$src_dir"/*; do
        [ -e "$f" ] || continue
        local basename
        basename=$(basename "$f")
        link_or_copy "$f" "$dest_dir/$basename"
    done
}

# ─── Main Installer ────────────────────────────────────────────

print_header

# Step 1: Target directory
TARGET_DIR="${1:-$(pwd)}"
prompt TARGET_DIR "Project directory" "$TARGET_DIR"
TARGET_DIR="$(cd "$TARGET_DIR" 2>/dev/null && pwd || echo "$TARGET_DIR")"
if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${RED}Error: $TARGET_DIR does not exist${NC}"
    exit 1
fi
echo -e "  ${GREEN}→${NC} Installing into: $TARGET_DIR"
echo ""

# Step 2: Project identity
prompt PROJECT_NAME "Project name" "$(basename "$TARGET_DIR")"
prompt PROJECT_DESCRIPTION "Project description (one line)" ""

echo ""

# Step 3: Tech stack
menu RUNTIME "Runtime:" "cloudflare-workers" "node" "deno" "python"

case "$RUNTIME" in
    cloudflare-workers) fw_default="hono" ;;
    node) fw_default="express" ;;
    python) fw_default="fastapi" ;;
    *) fw_default="none" ;;
esac
menu FRAMEWORK "Framework:" "hono" "express" "nextjs" "fastapi" "none"

case "$RUNTIME" in
    python) lang_default="python" ;;
    *) lang_default="typescript" ;;
esac
menu LANGUAGE "Language:" "typescript" "javascript" "python"

# Derive tool defaults from stack
case "$LANGUAGE" in
    typescript)
        TEST_RUNNER_DEFAULT="vitest"; LINTER_DEFAULT="eslint"; FORMATTER_DEFAULT="prettier"
        TYPECHECK_DEFAULT="npx tsc --noEmit"; TEST_DEFAULT="npm test"; LINT_DEFAULT="npm run lint"
        ;;
    javascript)
        TEST_RUNNER_DEFAULT="jest"; LINTER_DEFAULT="eslint"; FORMATTER_DEFAULT="prettier"
        TYPECHECK_DEFAULT=""; TEST_DEFAULT="npm test"; LINT_DEFAULT="npm run lint"
        ;;
    python)
        TEST_RUNNER_DEFAULT="pytest"; LINTER_DEFAULT="ruff"; FORMATTER_DEFAULT="black"
        TYPECHECK_DEFAULT=""; TEST_DEFAULT="pytest"; LINT_DEFAULT="ruff check ."
        ;;
esac

case "$RUNTIME" in
    cloudflare-workers) DEPLOY_DEFAULT="npx wrangler deploy"; DEV_DEFAULT="npx wrangler dev" ;;
    node) DEPLOY_DEFAULT=""; DEV_DEFAULT="npm run dev" ;;
    python) DEPLOY_DEFAULT=""; DEV_DEFAULT="python -m uvicorn main:app --reload" ;;
    *) DEPLOY_DEFAULT=""; DEV_DEFAULT="npm run dev" ;;
esac

TEST_RUNNER="$TEST_RUNNER_DEFAULT"
LINTER="$LINTER_DEFAULT"
FORMATTER="$FORMATTER_DEFAULT"

# Derive file extension from language
case "$LANGUAGE" in
    typescript) LANG_EXT="ts" ;;
    javascript) LANG_EXT="js" ;;
    python)     LANG_EXT="py" ;;
    *)          LANG_EXT="*" ;;
esac

TYPECHECK_CMD="$TYPECHECK_DEFAULT"
TEST_CMD="$TEST_DEFAULT"
LINT_CMD="$LINT_DEFAULT"
DEPLOY_CMD="$DEPLOY_DEFAULT"
DEV_CMD="$DEV_DEFAULT"

echo ""

# Step 4: Schema-first?
SCHEMA_ENABLED="false"
SCHEMA_DEFINITIONS=""
SCHEMA_GENERATED=""
SCHEMA_GEN_CMD=""
SCHEMA_CONFIG=""
read -rp "$(echo -e "${CYAN}Schema-first development?${NC} [y/N]: ")" schema_yn
if [[ "$schema_yn" =~ ^[Yy] ]]; then
    SCHEMA_ENABLED="true"
    prompt SCHEMA_DEFINITIONS "Schema definitions file" "schema/definitions.json"
    prompt SCHEMA_GENERATED "Generated types file" "generated/types.ts"
    prompt SCHEMA_GEN_CMD "Type generation command" "npm run generate:types"
    prompt SCHEMA_CONFIG "Config file" "schema/config.json"
fi

echo ""

# Step 5: Specs?
SPECS_ENABLED="false"
SPEC_DIRS='["specs/"]'
SPEC_PREFIX="PROJ"
read -rp "$(echo -e "${CYAN}Spec-driven development?${NC} [y/N]: ")" specs_yn
if [[ "$specs_yn" =~ ^[Yy] ]]; then
    SPECS_ENABLED="true"
    prompt SPEC_DIR_INPUT "Spec directories (comma-separated)" "specs/"
    # Convert to YAML list
    IFS=',' read -ra dirs <<< "$SPEC_DIR_INPUT"
    SPEC_DIRS="["
    for i in "${!dirs[@]}"; do
        [ "$i" -gt 0 ] && SPEC_DIRS+=", "
        SPEC_DIRS+="\"$(echo "${dirs[$i]}" | xargs)\""
    done
    SPEC_DIRS+="]"
    prompt SPEC_PREFIX "Spec ID prefix" "PROJ"
fi

echo ""

# Step 6: Agent count
menu AGENT_COUNT_STR "Number of agents:" "4 (Planner, Builder, Reviewer, Tester)" "5 (+Deployer)" "6 (+Deployer, +Docs)"
case "$AGENT_COUNT_STR" in
    "4"*) AGENT_COUNT=4 ;;
    "5"*) AGENT_COUNT=5 ;;
    "6"*) AGENT_COUNT=6 ;;
esac

BUILDER_MODE="auto-accept"

echo ""

# Step 7: Link mode
menu LINK_MODE "Installation mode:" "symlink" "copy"

echo ""

# Step 8: Credentials (Bitwarden)
CREDENTIALS_YAML="[]"
USE_BITWARDEN="false"
read -rp "$(echo -e "${CYAN}Use Bitwarden for credentials?${NC} [y/N]: ")" bw_yn
if [[ "$bw_yn" =~ ^[Yy] ]]; then
    USE_BITWARDEN="true"
    CREDENTIALS_YAML=""
    cred_index=0
    while true; do
        echo ""
        echo -e "${CYAN}Credential $((cred_index+1)):${NC}"
        prompt CRED_ALIAS "  Alias (e.g., cloudflare, github)" ""
        [ -z "$CRED_ALIAS" ] && break
        prompt CRED_BW_ENTRY "  Bitwarden entry name" ""
        [ -z "$CRED_BW_ENTRY" ] && break
        
        CREDENTIALS_YAML+="
  - alias: \"$CRED_ALIAS\"
    bitwarden_entry: \"$CRED_BW_ENTRY\"
    env_vars:"
        
        while true; do
            prompt CRED_ENV_NAME "  Env var name (empty to finish)" ""
            [ -z "$CRED_ENV_NAME" ] && break
            prompt CRED_FIELD "  Field (password/username/url/notes)" "password"
            CREDENTIALS_YAML+="
      - name: \"$CRED_ENV_NAME\"
        field: \"$CRED_FIELD\""
        done
        
        ((cred_index++))
        read -rp "  Add another credential? [y/N]: " more_yn
        [[ ! "$more_yn" =~ ^[Yy] ]] && break
    done
    [ -z "$CREDENTIALS_YAML" ] && CREDENTIALS_YAML="[]"
fi

# Derive source/test dirs
case "$FRAMEWORK" in
    nextjs) SOURCE_DIR="src"; TESTS_DIR="__tests__" ;;
    *) SOURCE_DIR="src"; TESTS_DIR="tests" ;;
esac
HANDOFFS_DIR="docs/agent-comms"
COVERAGE_THRESHOLD=80

echo ""
echo -e "${BLUE}━━━ Installing ━━━${NC}"
echo ""

# ─── Create .claude/ structure ─────────────────────────────────

CLAUDE_DIR="$TARGET_DIR/.claude"
mkdir -p "$CLAUDE_DIR"/{agents,commands,hooks,skills,scripts,rules}
mkdir -p "$CLAUDE_DIR/metrics"

# ─── Link/copy core files ──────────────────────────────────────

echo -e "${BOLD}Agents:${NC}"
link_dir_contents "$FRAMEWORK_DIR/core/agents" "$CLAUDE_DIR/agents"

echo ""
echo -e "${BOLD}Commands:${NC}"
link_dir_contents "$FRAMEWORK_DIR/core/commands" "$CLAUDE_DIR/commands"

echo ""
echo -e "${BOLD}Hooks:${NC}"
link_dir_contents "$FRAMEWORK_DIR/core/hooks" "$CLAUDE_DIR/hooks"

echo ""
echo -e "${BOLD}Skills:${NC}"
for skill_dir in "$FRAMEWORK_DIR"/core/skills/*/; do
    [ -d "$skill_dir" ] || continue
    local_name=$(basename "$skill_dir")
    mkdir -p "$CLAUDE_DIR/skills/$local_name"
    link_or_copy "$skill_dir/SKILL.md" "$CLAUDE_DIR/skills/$local_name/SKILL.md"
done

echo ""
echo -e "${BOLD}Scripts:${NC}"
link_dir_contents "$FRAMEWORK_DIR/core/scripts" "$CLAUDE_DIR/scripts"

echo ""
echo -e "${BOLD}Rules:${NC}"
link_dir_contents "$FRAMEWORK_DIR/core/rules" "$CLAUDE_DIR/rules"

# ─── Generate project-config.yaml ──────────────────────────────

echo ""
echo -e "${BOLD}Configuration:${NC}"
CONFIG_FILE="$CLAUDE_DIR/project-config.yaml"
# Use sed for template substitution (envsubst not always available)
sed \
    -e "s|\${PROJECT_NAME}|$PROJECT_NAME|g" \
    -e "s|\${PROJECT_DESCRIPTION}|$PROJECT_DESCRIPTION|g" \
    -e "s|\${RUNTIME}|$RUNTIME|g" \
    -e "s|\${FRAMEWORK}|$FRAMEWORK|g" \
    -e "s|\${LANGUAGE}|$LANGUAGE|g" \
    -e "s|\${TEST_RUNNER}|$TEST_RUNNER|g" \
    -e "s|\${LINTER}|$LINTER|g" \
    -e "s|\${FORMATTER}|$FORMATTER|g" \
    -e "s|\${DEPLOY_CMD}|$DEPLOY_CMD|g" \
    -e "s|\${DEV_CMD}|$DEV_CMD|g" \
    -e "s|\${SCHEMA_ENABLED}|$SCHEMA_ENABLED|g" \
    -e "s|\${SCHEMA_DEFINITIONS}|$SCHEMA_DEFINITIONS|g" \
    -e "s|\${SCHEMA_GENERATED}|$SCHEMA_GENERATED|g" \
    -e "s|\${SCHEMA_GEN_CMD}|$SCHEMA_GEN_CMD|g" \
    -e "s|\${SCHEMA_CONFIG}|$SCHEMA_CONFIG|g" \
    -e "s|\${SPECS_ENABLED}|$SPECS_ENABLED|g" \
    -e "s|\${SPEC_DIRS}|$SPEC_DIRS|g" \
    -e "s|\${SPEC_PREFIX}|$SPEC_PREFIX|g" \
    -e "s|\${SOURCE_DIR}|$SOURCE_DIR|g" \
    -e "s|\${TESTS_DIR}|$TESTS_DIR|g" \
    -e "s|\${HANDOFFS_DIR}|$HANDOFFS_DIR|g" \
    -e "s|\${AGENT_COUNT}|$AGENT_COUNT|g" \
    -e "s|\${BUILDER_MODE}|$BUILDER_MODE|g" \
    -e "s|\${TYPECHECK_CMD}|$TYPECHECK_CMD|g" \
    -e "s|\${TEST_CMD}|$TEST_CMD|g" \
    -e "s|\${LINT_CMD}|$LINT_CMD|g" \
    -e "s|\${COVERAGE_THRESHOLD}|$COVERAGE_THRESHOLD|g" \
    "$FRAMEWORK_DIR/templates/project-config.yaml.tmpl" > "$CONFIG_FILE.tmp"

# Replace credentials placeholder
if [ "$CREDENTIALS_YAML" = "[]" ]; then
    sed -i "s|  \${CREDENTIALS_YAML}|  []|" "$CONFIG_FILE.tmp"
else
    # Write credentials block
    sed -i "/\${CREDENTIALS_YAML}/d" "$CONFIG_FILE.tmp"
    echo "$CREDENTIALS_YAML" >> "$CONFIG_FILE.tmp"
fi

mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"
echo -e "  ${GREEN}WRITE${NC} $CONFIG_FILE"

# ─── Generate hooks.json ──────────────────────────────────────

if [ -f "$FRAMEWORK_DIR/templates/hooks.json.tmpl" ]; then
    cp "$FRAMEWORK_DIR/templates/hooks.json.tmpl" "$CLAUDE_DIR/hooks.json"
    echo -e "  ${GREEN}WRITE${NC} $CLAUDE_DIR/hooks.json"
fi

# ─── Generate settings.json ───────────────────────────────────

if [ -f "$FRAMEWORK_DIR/templates/settings.json.tmpl" ]; then
    cp "$FRAMEWORK_DIR/templates/settings.json.tmpl" "$CLAUDE_DIR/settings.json"
    echo -e "  ${GREEN}WRITE${NC} $CLAUDE_DIR/settings.json"
fi

# ─── Generate CLAUDE.md (only if not present) ──────────────────

CLAUDE_MD="$TARGET_DIR/CLAUDE.md"
if [ ! -f "$CLAUDE_MD" ]; then
    sed \
        -e "s|\${PROJECT_NAME}|$PROJECT_NAME|g" \
        -e "s|\${PROJECT_DESCRIPTION}|$PROJECT_DESCRIPTION|g" \
        -e "s|\${RUNTIME}|$RUNTIME|g" \
        -e "s|\${FRAMEWORK}|$FRAMEWORK|g" \
        -e "s|\${LANGUAGE}|$LANGUAGE|g" \
        -e "s|\${TYPECHECK_CMD}|$TYPECHECK_CMD|g" \
        -e "s|\${TEST_CMD}|$TEST_CMD|g" \
        -e "s|\${LINT_CMD}|$LINT_CMD|g" \
        -e "s|\${SOURCE_DIR}|$SOURCE_DIR|g" \
        -e "s|\${TESTS_DIR}|$TESTS_DIR|g" \
        -e "s|\${COVERAGE_THRESHOLD}|$COVERAGE_THRESHOLD|g" \
        -e "s|\${DEPLOY_CMD}|$DEPLOY_CMD|g" \
        -e "s|\${DEV_CMD}|$DEV_CMD|g" \
        -e "s|\${TEST_RUNNER}|$TEST_RUNNER|g" \
        -e "s|\${LINTER}|$LINTER|g" \
        -e "s|\${FORMATTER}|$FORMATTER|g" \
        -e "s|\${HANDOFFS_DIR}|$HANDOFFS_DIR|g" \
        -e "s|\${SCHEMA_ENABLED}|$SCHEMA_ENABLED|g" \
        -e "s|\${SCHEMA_DEFINITIONS}|$SCHEMA_DEFINITIONS|g" \
        -e "s|\${SCHEMA_GENERATED}|$SCHEMA_GENERATED|g" \
        "$FRAMEWORK_DIR/templates/CLAUDE.md.tmpl" > "$CLAUDE_MD"
    echo -e "  ${GREEN}WRITE${NC} $CLAUDE_MD"
else
    echo -e "  ${YELLOW}SKIP${NC} $CLAUDE_MD (already exists)"
fi

# ─── Generate project-stack.md rule ────────────────────────────

STACK_RULE="$CLAUDE_DIR/rules/project-stack.md"
if [ ! -f "$STACK_RULE" ] || [ -L "$STACK_RULE" ]; then
    rm -f "$STACK_RULE"
    sed \
        -e "s|\${RUNTIME}|$RUNTIME|g" \
        -e "s|\${FRAMEWORK}|$FRAMEWORK|g" \
        -e "s|\${LANGUAGE}|$LANGUAGE|g" \
        -e "s|\${LANG_EXT}|$LANG_EXT|g" \
        -e "s|\${SOURCE_DIR}|$SOURCE_DIR|g" \
        "$FRAMEWORK_DIR/templates/rules/project-stack.md.tmpl" > "$STACK_RULE"
    echo -e "  ${GREEN}WRITE${NC} $STACK_RULE"
fi

# ─── Generate project-domain.md placeholder ────────────────────

DOMAIN_RULE="$CLAUDE_DIR/rules/project-domain.md"
if [ ! -f "$DOMAIN_RULE" ]; then
    sed \
        -e "s|\${PROJECT_NAME}|$PROJECT_NAME|g" \
        "$FRAMEWORK_DIR/templates/rules/project-domain.md.tmpl" > "$DOMAIN_RULE"
    echo -e "  ${GREEN}WRITE${NC} $DOMAIN_RULE"
else
    echo -e "  ${YELLOW}SKIP${NC} $DOMAIN_RULE (already exists)"
fi

# ─── Symlink launch script ────────────────────────────────────

mkdir -p "$TARGET_DIR/scripts/ivans-workflow"
link_or_copy "$FRAMEWORK_DIR/scripts/launch-tmux-agents.sh" "$TARGET_DIR/scripts/ivans-workflow/launch.sh"
link_or_copy "$FRAMEWORK_DIR/scripts/monitor-agents.sh" "$TARGET_DIR/scripts/ivans-workflow/monitor.sh"

# ─── Create handoffs directory ─────────────────────────────────

mkdir -p "$TARGET_DIR/$HANDOFFS_DIR"
echo -e "  ${GREEN}MKDIR${NC} $TARGET_DIR/$HANDOFFS_DIR"

# ─── Update .gitignore ─────────────────────────────────────────

GITIGNORE="$TARGET_DIR/.gitignore"
if [ -f "$GITIGNORE" ]; then
    for pattern in ".claude/settings.local.json" ".claude/metrics/" "*.env" ".dev.vars"; do
        if ! grep -qF "$pattern" "$GITIGNORE"; then
            echo "$pattern" >> "$GITIGNORE"
            echo -e "  ${GREEN}APPEND${NC} $GITIGNORE: $pattern"
        fi
    done
else
    cat > "$GITIGNORE" <<'EOF'
.claude/settings.local.json
.claude/metrics/
*.env
.dev.vars
EOF
    echo -e "  ${GREEN}WRITE${NC} $GITIGNORE"
fi

# ─── Summary ───────────────────────────────────────────────────

echo ""
echo -e "${BLUE}━━━ Installation Complete ━━━${NC}"
echo ""
echo -e "  ${BOLD}Project:${NC}    $PROJECT_NAME"
echo -e "  ${BOLD}Stack:${NC}      $RUNTIME / $FRAMEWORK / $LANGUAGE"
echo -e "  ${BOLD}Agents:${NC}     $AGENT_COUNT"
echo -e "  ${BOLD}Schema:${NC}     $SCHEMA_ENABLED"
echo -e "  ${BOLD}Specs:${NC}      $SPECS_ENABLED"
echo -e "  ${BOLD}Mode:${NC}       $LINK_MODE"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Review .claude/project-config.yaml and adjust as needed"
echo "  2. Edit .claude/rules/project-domain.md with your domain rules"
echo "  3. Launch agents: scripts/ivans-workflow/launch.sh"
echo "  4. Start with: /workflow-start <TASK-ID>"
echo ""
echo -e "${GREEN}Done!${NC}"
