#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Remove Ivan's Workflow from a project (cleans .claude/ symlinks only).

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_DIR="${1:-.}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
CLAUDE_DIR="$PROJECT_DIR/.claude"

echo -e "${BLUE}═══ Ivan's Workflow — Uninstall ═══${NC}"
echo ""
echo -e "Project: ${GREEN}$PROJECT_DIR${NC}"
echo ""

if [ ! -d "$CLAUDE_DIR" ]; then
    echo -e "${YELLOW}No .claude/ directory found. Nothing to remove.${NC}"
    exit 0
fi

# Confirm
read -rp "This will remove Ivan's Workflow symlinks from .claude/. Continue? [y/N] " answer
if [[ ! "$answer" =~ ^[Yy] ]]; then
    echo "Aborted."
    exit 0
fi

# Remove symlinks that point to ivans-workflow (preserve local files)
removed=0
find "$CLAUDE_DIR" -type l | while read -r link; do
    target=$(readlink "$link" 2>/dev/null || true)
    if [[ "$target" == *"ivans-workflow"* ]]; then
        rm "$link"
        echo -e "  ${RED}✗${NC} Removed: ${link#$PROJECT_DIR/}"
        ((removed++)) || true
    fi
done

# Remove generated files (only if they have the Ivan's Workflow header)
for f in "$CLAUDE_DIR/hooks.json" "$CLAUDE_DIR/settings.json" "$CLAUDE_DIR/project-config.yaml"; do
    if [ -f "$f" ] && head -1 "$f" 2>/dev/null | grep -qi "ivan"; then
        rm "$f"
        echo -e "  ${RED}✗${NC} Removed: ${f#$PROJECT_DIR/}"
    fi
done

# Remove launch script symlink
LAUNCH_LINK="$PROJECT_DIR/scripts/ivans-workflow/launch.sh"
if [ -L "$LAUNCH_LINK" ]; then
    rm "$LAUNCH_LINK"
    rmdir "$PROJECT_DIR/scripts/ivans-workflow" 2>/dev/null || true
    echo -e "  ${RED}✗${NC} Removed: scripts/ivans-workflow/launch.sh"
fi

# Clean up empty directories
for d in "$CLAUDE_DIR/agents" "$CLAUDE_DIR/commands" "$CLAUDE_DIR/hooks" "$CLAUDE_DIR/skills" "$CLAUDE_DIR/scripts" "$CLAUDE_DIR/rules"; do
    if [ -d "$d" ] && [ -z "$(ls -A "$d" 2>/dev/null)" ]; then
        rmdir "$d"
        echo -e "  ${RED}✗${NC} Removed empty: ${d#$PROJECT_DIR/}"
    fi
done

echo ""
echo -e "${GREEN}Uninstall complete.${NC}"
echo ""
echo "Preserved:"
echo "  - CLAUDE.md (your project constitution)"
echo "  - .claude/rules/project-domain.md (your domain rules)"
echo "  - docs/agent-comms/ (handoff files)"
echo "  - Any locally-created (non-symlinked) files"
echo ""
echo "To fully remove .claude/: rm -rf $CLAUDE_DIR"
