#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Update framework and re-link into installed projects.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}═══ Ivan's Workflow — Update ═══${NC}"
echo ""

# Pull latest changes
cd "$SCRIPT_DIR"
echo -e "Pulling latest from origin..."
if git pull --ff-only 2>/dev/null; then
    echo -e "${GREEN}Framework updated.${NC}"
else
    echo -e "${YELLOW}Could not fast-forward. Check for local changes.${NC}"
    git status --short
    exit 1
fi

echo ""

# If a project directory is provided, re-run installer to update symlinks
if [ -n "${1:-}" ]; then
    PROJECT_DIR="$(cd "$1" && pwd)"
    if [ -f "$PROJECT_DIR/.claude/project-config.yaml" ]; then
        echo -e "Re-linking into project: ${GREEN}$PROJECT_DIR${NC}"
        "$SCRIPT_DIR/install.sh" "$PROJECT_DIR"
    else
        echo -e "${YELLOW}No project-config.yaml found at $PROJECT_DIR/.claude/${NC}"
        echo "Run install.sh to set up a new project."
    fi
else
    echo "Framework updated. To update a project's symlinks:"
    echo "  $SCRIPT_DIR/install.sh /path/to/your/project"
    echo ""
    echo "If you used symlink mode (default), core files already reflect the update."
fi
