#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Parameterized tmux agent launcher — reads project-config.yaml

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ─── Configuration ─────────────────────────────────────────────

PROJECT_DIR="${1:-.}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
CONFIG="$PROJECT_DIR/.claude/project-config.yaml"

if [ ! -f "$CONFIG" ]; then
    echo -e "${RED}Error: No project-config.yaml found at $CONFIG${NC}"
    echo "Run install.sh first to set up Ivan's Workflow in your project."
    exit 1
fi

# Parse config
config_val() {
    awk -v key="$1" '$1 == key":" { gsub(/"/, "", $2); print $2 }' "$CONFIG" 2>/dev/null
}

PROJECT_NAME=$(config_val "name")
AGENT_COUNT=$(config_val "count")
BUILDER_MODE=$(config_val "builder_mode")

AGENT_COUNT="${AGENT_COUNT:-4}"
BUILDER_MODE="${BUILDER_MODE:-auto-accept}"
PROJECT_NAME="${PROJECT_NAME:-project}"

# Session name
SESSION="ivans-workflow"
if [ -n "$PROJECT_NAME" ]; then
    SESSION="ivan-${PROJECT_NAME// /-}"
    SESSION="${SESSION,,}"  # lowercase
fi

# ─── Kill mode ─────────────────────────────────────────────────

if [ "${1:-}" = "--kill" ] || [ "${2:-}" = "--kill" ]; then
    echo -e "${YELLOW}Killing session: $SESSION${NC}"
    tmux kill-session -t "$SESSION" 2>/dev/null && \
        echo -e "${GREEN}Session terminated.${NC}" || \
        echo -e "${RED}No active session found.${NC}"
    exit 0
fi

# ─── Pre-flight checks ────────────────────────────────────────

echo -e "${BLUE}═══ Ivan's Workflow — Agent Launcher ═══${NC}"
echo -e "Project:  ${GREEN}$PROJECT_NAME${NC}"
echo -e "Agents:   ${GREEN}$AGENT_COUNT${NC}"
echo -e "Builder:  ${GREEN}$BUILDER_MODE${NC}"
echo -e "Session:  ${GREEN}$SESSION${NC}"
echo ""

# Check prerequisites
for cmd in tmux claude; do
    if ! command -v "$cmd" &>/dev/null; then
        echo -e "${RED}Error: '$cmd' not found. Please install it first.${NC}"
        exit 1
    fi
done

# Kill existing session if running
if tmux has-session -t "$SESSION" 2>/dev/null; then
    echo -e "${YELLOW}Existing session found. Killing it...${NC}"
    tmux kill-session -t "$SESSION"
    sleep 1
fi

# ─── Load credentials ─────────────────────────────────────────

CRED_SCRIPT="$PROJECT_DIR/.claude/scripts/load-project-credentials.sh"
if [ -f "$CRED_SCRIPT" ]; then
    echo -e "${BLUE}Loading credentials...${NC}"
    if source "$CRED_SCRIPT" 2>/dev/null; then
        echo -e "${GREEN}Credentials loaded.${NC}"
    else
        echo -e "${YELLOW}Some credentials failed to load.${NC}"
        read -rp "Continue without all credentials? [y/N] " answer
        if [[ ! "$answer" =~ ^[Yy] ]]; then
            echo "Aborted. Run: export BW_SESSION=\$(bw unlock --raw)"
            exit 1
        fi
    fi
else
    echo -e "${YELLOW}No credential loader found — skipping.${NC}"
fi
echo ""

# ─── Agent definitions ─────────────────────────────────────────

AGENTS=("planner" "builder" "reviewer" "tester")
EMOJIS=("🔵" "🟢" "🟡" "🟣")
MODES=("plan" "$BUILDER_MODE" "interactive" "interactive")

if [ "$AGENT_COUNT" -ge 5 ]; then
    AGENTS+=("deployer")
    EMOJIS+=("🔴")
    MODES+=("interactive")
fi
if [ "$AGENT_COUNT" -ge 6 ]; then
    AGENTS+=("docs")
    EMOJIS+=("🟠")
    MODES+=("interactive")
fi

# ─── Create tmux session ──────────────────────────────────────

echo -e "${BLUE}Creating tmux session...${NC}"
tmux new-session -d -s "$SESSION" -n "${EMOJIS[0]} ${AGENTS[0]}" -x 200 -y 50

# Create additional windows
for i in $(seq 1 $((${#AGENTS[@]} - 1))); do
    tmux new-window -t "$SESSION" -n "${EMOJIS[$i]} ${AGENTS[$i]}"
done

# ─── Launch agents ─────────────────────────────────────────────

for i in $(seq 0 $((${#AGENTS[@]} - 1))); do
    AGENT="${AGENTS[$i]}"
    MODE="${MODES[$i]}"
    EMOJI="${EMOJIS[$i]}"
    
    echo -e "  ${EMOJI} Starting ${AGENT}..."
    
    # Set environment and cd to project
    tmux send-keys -t "$SESSION:$i" "cd '$PROJECT_DIR'" Enter
    tmux send-keys -t "$SESSION:$i" "export IVAN_AGENT_ROLE=$AGENT" Enter
    
    # Build claude command with appropriate flags
    CLAUDE_CMD="claude"
    if [ "$MODE" = "auto-accept" ]; then
        CLAUDE_CMD="claude --dangerously-skip-permissions"
    fi
    
    # Launch claude
    tmux send-keys -t "$SESSION:$i" "$CLAUDE_CMD" Enter
    
    # Wait for Claude to be ready (look for prompt)
    sleep 3
    
    # Send initialization prompt
    SKILL_PATH=".claude/skills/${AGENT}-agent/SKILL.md"
    INIT_MSG="I am the ${AGENT^} agent. Read my skill at ${SKILL_PATH} and follow its protocol. Project config is at .claude/project-config.yaml. Acknowledge with one line: your role and what you'll do."
    
    tmux send-keys -t "$SESSION:$i" "$INIT_MSG" Enter
    
    # Staggered startup
    sleep 2
done

# ─── Summary ───────────────────────────────────────────────────

echo ""
echo -e "${GREEN}═══ All agents launched! ═══${NC}"
echo ""
echo "Window assignments:"
for i in $(seq 0 $((${#AGENTS[@]} - 1))); do
    printf "  Ctrl+b %d  →  %s %s\n" "$i" "${EMOJIS[$i]}" "${AGENTS[$i]^}"
done
echo ""
echo "Commands:"
echo "  tmux attach -t $SESSION     # Attach to session"
echo "  Ctrl+b d                    # Detach"
echo "  Ctrl+b [0-$((${#AGENTS[@]}-1))]                # Switch window"
echo "  $(basename "$0") --kill     # Terminate all agents"
echo ""

# Auto-attach
tmux attach -t "$SESSION"
