#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Monitor agent health in tmux session

set -uo pipefail

SESSION="${1:-ivans-workflow}"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    echo "No active session: $SESSION"
    exit 1
fi

echo "═══ Agent Health — $SESSION ═══"
echo ""

WINDOWS=$(tmux list-windows -t "$SESSION" -F "#{window_index}:#{window_name}" 2>/dev/null)
while IFS= read -r win; do
    IDX="${win%%:*}"
    NAME="${win#*:}"
    
    # Check if window has active process
    PANE_PID=$(tmux list-panes -t "$SESSION:$IDX" -F "#{pane_pid}" 2>/dev/null | head -1)
    
    if [ -n "$PANE_PID" ] && kill -0 "$PANE_PID" 2>/dev/null; then
        echo "  [$IDX] $NAME — ✓ running (pid: $PANE_PID)"
    else
        echo "  [$IDX] $NAME — ✗ not running"
    fi
done <<< "$WINDOWS"

echo ""
echo "Attach: tmux attach -t $SESSION"
