#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Interactive Bitwarden credential setup for a project

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}═══ Ivan's Workflow — Credential Setup ═══${NC}"
echo ""

# Check Bitwarden CLI
if ! command -v bw &>/dev/null; then
    echo -e "${RED}Bitwarden CLI not installed.${NC}"
    echo "Install: https://bitwarden.com/help/cli/"
    exit 1
fi

# Check login status
BW_STATUS=$(bw status 2>/dev/null | jq -r '.status' 2>/dev/null || echo "error")
case "$BW_STATUS" in
    unauthenticated)
        echo -e "${RED}Not logged in. Run: bw login${NC}"
        exit 1
        ;;
    locked)
        echo -e "${YELLOW}Vault is locked.${NC}"
        echo "Run: export BW_SESSION=\$(bw unlock --raw)"
        read -rp "Or enter BW_SESSION token: " BW_SESSION
        export BW_SESSION
        ;;
    unlocked)
        echo -e "${GREEN}Vault is unlocked.${NC}"
        ;;
    *)
        echo -e "${RED}Unknown status: $BW_STATUS${NC}"
        exit 1
        ;;
esac

# Store master password in keyring (optional)
echo ""
read -rp "Store master password in GNOME Keyring for auto-unlock? [y/N] " store_pw
if [[ "$store_pw" =~ ^[Yy] ]]; then
    if command -v secret-tool &>/dev/null; then
        echo "Enter your Bitwarden master password:"
        secret-tool store --label='Bitwarden' bitwarden master
        echo -e "${GREEN}Stored in GNOME Keyring.${NC}"
    else
        echo -e "${YELLOW}secret-tool not available. Install libsecret-tools.${NC}"
    fi
fi

echo ""
echo -e "${GREEN}Credential setup complete.${NC}"
echo "Configure project credentials in .claude/project-config.yaml under the credentials: section."
