#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Credential Helper — Retrieves credentials from Bitwarden with three-strategy fallback.
# Reads credential definitions from project-config.yaml.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/.claude/project-config.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

# ─── Bitwarden Session Management ─────────────────────────────

get_bw_session() {
    # Strategy 1: Environment variable already set and valid
    if [ -n "${BW_SESSION:-}" ]; then
        if bw status --session "$BW_SESSION" 2>/dev/null | grep -q '"unlocked"'; then
            echo "$BW_SESSION"
            return 0
        fi
    fi

    # Strategy 2: GNOME Keyring auto-unlock
    local master_pw
    master_pw=$(get_keyring_password 2>/dev/null || true)
    if [ -n "$master_pw" ]; then
        local session
        # SECURITY: pipe via stdin, NEVER as CLI argument (visible in ps aux)
        session=$(printf '%s' "$master_pw" | bw unlock --raw 2>/dev/null || true)
        if [ -n "$session" ] && [ ${#session} -gt 50 ]; then
            echo "$session"
            return 0
        fi
    fi

    # Strategy 3: Ask user
    echo "" >&2
    echo -e "${YELLOW}═══ Bitwarden Unlock Required ═══${NC}" >&2
    echo "" >&2
    echo "Run this in your terminal:" >&2
    echo -e "  ${GREEN}export BW_SESSION=\$(bw unlock --raw)${NC}" >&2
    echo "" >&2
    echo "Then either:" >&2
    echo "  a) Re-run this command, or" >&2
    echo "  b) Paste the BW_SESSION value when prompted" >&2
    echo "" >&2

    # If running interactively, prompt directly
    if [ -t 0 ]; then
        read -rp "BW_SESSION token (or press Enter to abort): " session
        if [ -n "$session" ] && [ ${#session} -gt 50 ]; then
            echo "$session"
            return 0
        fi
    fi

    return 1
}

get_keyring_password() {
    # Ensure D-Bus is available (needed in tmux/SSH/non-desktop shells)
    local dbus_addr="${DBUS_SESSION_BUS_ADDRESS:-}"
    if [ -z "$dbus_addr" ]; then
        local uid
        uid=$(id -u)
        local dbus_path="/run/user/$uid/bus"
        if [ -S "$dbus_path" ]; then
            export DBUS_SESSION_BUS_ADDRESS="unix:path=$dbus_path"
        fi
    fi

    secret-tool lookup bitwarden master 2>/dev/null
}

# ─── Config Parsing (awk-based — no yq dependency) ────────────

parse_config_entry() {
    local alias="$1"
    [ ! -f "$CONFIG_FILE" ] && return 1
    awk -v alias="$alias" '
        /^[[:space:]]*- alias:/ {
            gsub(/^[[:space:]]*- alias:[[:space:]]*/, "")
            gsub(/"/, "")
            current_alias = $0
        }
        /bitwarden_entry:/ && current_alias == alias {
            gsub(/^.*bitwarden_entry:[[:space:]]*/, "")
            gsub(/"/, "")
            gsub(/[[:space:]]*$/, "")
            print
            exit
        }
    ' "$CONFIG_FILE" 2>/dev/null
}

list_credentials() {
    [ ! -f "$CONFIG_FILE" ] && { echo -e "${YELLOW}No project-config.yaml found${NC}"; return 1; }
    echo "Configured credentials:"
    awk '
        /^[[:space:]]*- alias:/ {
            gsub(/^[[:space:]]*- alias:[[:space:]]*/, "")
            gsub(/"/, "")
            alias = $0
        }
        /bitwarden_entry:/ {
            gsub(/^.*bitwarden_entry:[[:space:]]*/, "")
            gsub(/"/, "")
            gsub(/[[:space:]]*$/, "")
            entry = $0
            printf "  %-20s → %s\n", alias, entry
        }
    ' "$CONFIG_FILE" 2>/dev/null
}

# ─── Credential Retrieval ──────────────────────────────────────

get_credential() {
    local alias="$1"
    local field="${2:-password}"

    local bw_entry
    bw_entry=$(parse_config_entry "$alias")
    if [ -z "$bw_entry" ]; then
        echo -e "${RED}Error: No credential alias '$alias' in $CONFIG_FILE${NC}" >&2
        echo "Configured aliases:" >&2
        list_credentials >&2
        return 1
    fi

    local session
    session=$(get_bw_session) || {
        echo -e "${RED}Error: Could not unlock Bitwarden${NC}" >&2
        return 1
    }

    local item_json
    item_json=$(bw get item "$bw_entry" --session "$session" 2>/dev/null) || {
        echo -e "${RED}Error: Bitwarden entry '$bw_entry' not found${NC}" >&2
        return 1
    }

    case "$field" in
        password) echo "$item_json" | jq -r '.login.password // empty' ;;
        username) echo "$item_json" | jq -r '.login.username // empty' ;;
        url)      echo "$item_json" | jq -r '.login.uris[0].uri // empty' ;;
        notes)    echo "$item_json" | jq -r '.notes // empty' ;;
        *)        echo -e "${RED}Unknown field: $field (use: password|username|url|notes)${NC}" >&2; return 1 ;;
    esac
}

# ─── Load All Project Credentials ──────────────────────────────

load_all_credentials() {
    [ ! -f "$CONFIG_FILE" ] && {
        echo -e "${YELLOW}No project-config.yaml found — skipping credential load${NC}" >&2
        return 0
    }

    # Check if credentials section exists and has entries
    if ! grep -q "^credentials:" "$CONFIG_FILE" 2>/dev/null; then
        echo -e "${YELLOW}No credentials configured in project-config.yaml${NC}"
        return 0
    fi

    local session
    session=$(get_bw_session) || {
        echo -e "${RED}Failed to unlock Bitwarden${NC}" >&2
        return 1
    }

    local loaded=0
    local failed=0
    local current_alias="" current_entry=""

    while IFS= read -r line; do
        # Match alias line
        if [[ "$line" =~ ^[[:space:]]*-[[:space:]]*alias:[[:space:]]*(.*) ]]; then
            current_alias="${BASH_REMATCH[1]}"
            current_alias="${current_alias//\"/}"
            current_alias="${current_alias## }"
            current_alias="${current_alias%% }"
            current_entry=""
        # Match bitwarden_entry line
        elif [[ "$line" =~ bitwarden_entry:[[:space:]]*(.*) ]]; then
            current_entry="${BASH_REMATCH[1]}"
            current_entry="${current_entry//\"/}"
            current_entry="${current_entry## }"
            current_entry="${current_entry%% }"
        # Match env var name line
        elif [[ "$line" =~ ^[[:space:]]*-[[:space:]]*name:[[:space:]]*(.*) ]] && [ -n "$current_entry" ]; then
            local env_name="${BASH_REMATCH[1]}"
            env_name="${env_name//\"/}"
            env_name="${env_name## }"
            env_name="${env_name%% }"
            # Read next line for field
            read -r field_line || true
            local field="password"
            if [[ "$field_line" =~ field:[[:space:]]*(.*) ]]; then
                field="${BASH_REMATCH[1]}"
                field="${field//\"/}"
                field="${field## }"
                field="${field%% }"
            fi

            # Retrieve from Bitwarden and export
            local value
            local jq_path=".login.$field"
            [ "$field" = "url" ] && jq_path=".login.uris[0].uri"
            [ "$field" = "notes" ] && jq_path=".notes"

            value=$(bw get item "$current_entry" --session "$session" 2>/dev/null | jq -r "$jq_path // empty" 2>/dev/null) || true
            if [ -n "$value" ]; then
                export "$env_name=$value"
                echo -e "  ${GREEN}✓${NC} $env_name (from $current_alias)"
                ((loaded++))
            else
                echo -e "  ${RED}✗${NC} $env_name (failed: $current_alias → $current_entry)"
                ((failed++))
            fi
        fi
    done < <(awk '/^credentials:/,/^[a-z]/' "$CONFIG_FILE" | head -100)

    echo ""
    echo -e "Loaded: ${GREEN}$loaded${NC}, Failed: ${RED}$failed${NC}"
    [ "$failed" -eq 0 ]
}

# ─── Status Check ──────────────────────────────────────────────

check_status() {
    echo "═══ Credential Manager Status ═══"
    echo ""

    # Bitwarden CLI
    if command -v bw &>/dev/null; then
        local bw_status
        bw_status=$(bw status 2>/dev/null | jq -r '.status' 2>/dev/null || echo "error")
        case "$bw_status" in
            unlocked)        echo -e "Bitwarden:  ${GREEN}unlocked${NC}" ;;
            locked)          echo -e "Bitwarden:  ${YELLOW}locked${NC} (run: bw unlock)" ;;
            unauthenticated) echo -e "Bitwarden:  ${RED}not logged in${NC} (run: bw login)" ;;
            *)               echo -e "Bitwarden:  ${RED}$bw_status${NC}" ;;
        esac
    else
        echo -e "Bitwarden:  ${RED}not installed${NC}"
    fi

    # BW_SESSION
    if [ -n "${BW_SESSION:-}" ]; then
        echo -e "BW_SESSION: ${GREEN}set${NC} (${#BW_SESSION} chars)"
    else
        echo -e "BW_SESSION: ${YELLOW}not set${NC}"
    fi

    # GNOME Keyring
    local keyring_pw
    keyring_pw=$(get_keyring_password 2>/dev/null || true)
    if [ -n "$keyring_pw" ]; then
        echo -e "Keyring:    ${GREEN}master password stored${NC}"
    else
        echo -e "Keyring:    ${YELLOW}no master password${NC}"
    fi

    # Project credentials
    echo ""
    if [ -f "$CONFIG_FILE" ]; then
        list_credentials
    else
        echo -e "${YELLOW}No project-config.yaml found at $CONFIG_FILE${NC}"
    fi
}

# ─── Main ──────────────────────────────────────────────────────

case "${1:-help}" in
    get)
        [ -z "${2:-}" ] && { echo "Usage: credential-helper.sh get <alias> [field]"; exit 1; }
        get_credential "$2" "${3:-password}"
        ;;
    load)
        load_all_credentials
        ;;
    list)
        list_credentials
        ;;
    status)
        check_status
        ;;
    *)
        echo "Ivan's Workflow — Credential Helper"
        echo ""
        echo "Usage:"
        echo "  credential-helper.sh get <alias> [field]  Get a credential (field: password|username|url|notes)"
        echo "  credential-helper.sh load                 Load all project credentials into env"
        echo "  credential-helper.sh list                 List configured credential aliases"
        echo "  credential-helper.sh status               Check Bitwarden and keyring status"
        ;;
esac
