#!/usr/bin/env bash
# Generated by Ivan's Workflow — https://github.com/No-Smoke/ivans-workflow
# Load Project Credentials — Source this file to load all credentials into the current shell.
# Usage: source .claude/scripts/load-project-credentials.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"$SCRIPT_DIR/credential-helper.sh" load
